### ISSUE TITLE
docker-neo4j gds plugin broken url - version: <4.4.6

### ISSUE THREAD

**Issue by sathishdeveloper** [neo4j/graph-data-science#231]
At docker-neo4j, version <= 4.4.5, the graph-data-science plugin url has been configured with: https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms. This URL is inaccessible/broken now.

I understand the later versions are migrated to https://graphdatascience.ninja/versions.json.

Also, for version 4.4.12, configuring the property '**_dbms.directories.data_**' with custom path has not been considered and reported with error message:

```Consider unsetting SECURE_FILE_PERMISSIONS environment variable, to enable docker to write to /data/databases.```

The configuration
```
securityContext:
  runAsNonRoot: true
config:
  dbms.logs.user.stdout_enabled: "true"
  dbms.directories.logs: "/test"
  dbms.directories.data: "/test/neo4j-data"
  dbms.security.procedures.unrestricted: "gds.*"
```

Also tried with the environment companions for the above properties
```
env:
  NEO4J_dbms_directories_data: "/test/neo4j-data"
  NEO4J_dbms_logs_user_stdout__enabled: "true"
  NEO4J_dbms_directories_logs: "/test"
  NEO4J_dbms_security_procedures_unrestricted: "gds.*"
```
