### ISSUE TITLE
graph-data-science is not working with neo4j:latest in docker compose

### ISSUE THREAD

**Issue by abhinavmishra590** [neo4j/graph-data-science#269]
**Describe the bug**
graph-data-science is not working with neo4j:latest in docker compose

**To Reproduce**
This is the docker-compose.yml I am using in Macbook M1 Pro

 ```
 neo4j:
    image: neo4j:latest
    platform: linux/amd64
    restart: always
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/new4jnew4j
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
```
And I get following error `ERROR: No compatible "graph-data-science" plugin found for Neo4j 5.7.0`

I tired to specify versions of neo4j but they either throw same error or neo4j doesn't start.

Docker desktop version: 4.19.0 
Neo4j version: 5.7.4
Operating system: Macbook M1 Pro

**Expected behavior**
Neo4J to start successfully and graph-data-science plugin to work

**Additional context**

**Comment by Mats-SX** [comment]
Hello @abhinavmishra590 and thanks for reaching out to us.

I made a small change to your compose file into this content:

```
version: '4.15'

services:
  neo4j:
    image: neo4j:latest
    platform: linux/amd64
    restart: always
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/new4jnew4j
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
```

With that I was able to start using `docker compose create` and `docker compose start neo4j`. It succeeded and I could verify by going to `0.0.0.0:7474` and running Cypher queries in Neo4j Browser.

So it seems to be working fine. Could you maybe try another time?

All the best
Mats
